mariadb:
  auth:
    rootPassword: my-root-password
    database: mydatabase
    username: myuser
    password: mypassword

  primary:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi

  secondary:
    replicaCount: 1

  metrics:
    enabled: false
