apiVersion: v2
name: apache
description: An Apache server Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 2.4.46
dependencies:
  - name: apache
    version: 11.0.5
    repository: https://charts.bitnami.com/bitnami
