# values.yaml

## Apache server settings
apache:
  replicaCount: 1
  image:
    repository: bitnami/apache
    tag: latest
  service:
    type: LoadBalancer
    port: 80

## Configuration to mount the index.html ConfigMap
extraVolumeMounts:
  - name: apache-index
    mountPath: /opt/bitnami/apache/htdocs/index.html
    subPath: index.html

extraVolumes:
  - name: apache-index
    configMap:
      name: apache-index
