# values.yaml

## Apache server settings
apache:
  replicaCount: 1
  image:
    repository: bitnami/apache
    tag: latest
  service:
    type: LoadBalancer
    port: 80

## Configuration to mount the PHP file ConfigMap
extraVolumeMounts:
  - name: php-endpoints
    mountPath: /var/www/html/endpoints
    subPath: messages.php

extraVolumes:
  - name: php-endpoints
    configMap:
      name: php-endpoints
