replicaCount: 1
image:
  repository: bitnami/apache
  tag: latest
service:
  type: LoadBalancer
  port: 80
extraVolumeMounts:
  - name: apache-index
    mountPath: /opt/bitnami/apache/htdocs/index.html
    subPath: index.html
  - name: php-endpoints
    mountPath: /opt/bitnami/apache/htdocs/endpoints/messages.php
    subPath: messages.php
extraVolumes:
  - name: apache-index
    configMap:
      name: apache-index
  - name: php-endpoints
    configMap:
      name: php-endpoints
