apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - containerPort: 80
      - name: debug
        image: busybox
        command: ['sh', '-c', 'while true; do sleep 3600; done']
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: apache-index
          mountPath: /opt/bitnami/apache/htdocs/index.html
          subPath: index.html
        - name: php-endpoints
          mountPath: /opt/bitnami/apache/htdocs/endpoints/messages.php
          subPath: messages.php
      volumes:
      - name: apache-index
        configMap:
          name: apache-index
      - name: php-endpoints
        configMap:
          name: php-endpoints
